2020-04-11 22:13:50,683 : INFO : Machine : Mission Pinball Framework Core Engine v0.52.9
2020-04-11 22:13:50,683 : INFO : Machine : Command line arguments: {'syslog_address': None, 'mpfconfigfile': 'c:\\users\\mission pinball\\appdata\\local\\programs\\python\\python35\\lib\\site-packages\\mpf\\mpfconfig.yaml', 'jsonlogging': False, 'create_config_cache': True, 'mc_file_name': None, 'logfile': 'logs\\2020-04-11-22-13-50-mpf-DESKTOP-I5I6D25.log', 'no_load_cache': False, 'production': False, 'bcp': True, 'consoleloglevel': 20, 'pause': False, 'configfile': ['config.yaml'], 'force_assets_load': False, 'no_sound': False, 'text_ui': True, 'loglevel': 15, 'force_platform': None}
2020-04-11 22:13:50,683 : INFO : Machine : MPF path: c:\users\mission pinball\appdata\local\programs\python\python35\lib\site-packages\mpf
2020-04-11 22:13:50,683 : INFO : Machine : Machine path: E:\POKEMON - 4 - ATTRACT AND HIGH SCORE DISPLAYS
2020-04-11 22:13:50,683 : INFO : Machine : Platform: win32
2020-04-11 22:13:50,683 : INFO : Machine : Python executable location: c:\users\mission pinball\appdata\local\programs\python\python35\python.exe
2020-04-11 22:13:50,683 : INFO : Machine : Python version: 3.5.4 (64-bit)
2020-04-11 22:13:50,683 : INFO : Machine : Machine config file #1: config.yaml
2020-04-11 22:13:50,699 : INFO : ConfigProcessor : Loading config from cache: C:\Users\MISSIO~1\AppData\Local\Temp\1d59add9599c514c5f7c5be61c73be75.mpf_cache
2020-04-11 22:13:50,714 : INFO : Machine : Initialise MPF.
2020-04-11 22:13:51,277 : INFO : FAST : Connecting to com4 at 921600bps
2020-04-11 22:13:51,324 : INFO : FAST : Connected! Processor: NET, Board Type: FP-CPU-002-2, Firmware: 01.01
2020-04-11 22:13:51,324 : INFO : EventManager : Event: ======'machine_var_fast_net_firmware'====== Args={'change': True, 'value': '01.01', 'prev_value': None}
2020-04-11 22:13:51,324 : INFO : EventManager : Event: ======'machine_var_fast_net_model'====== Args={'change': True, 'value': 'FP-CPU-002-2', 'prev_value': None}
2020-04-11 22:13:51,324 : WARNING : FAST : Not resetting FAST NET because firmware is currently broken.
2020-04-11 22:13:51,386 : INFO : FAST : Connecting to com5 at 921600bps
2020-04-11 22:13:51,433 : INFO : FAST : Connected! Processor: RGB, Board Type: FP-CPU-002-2, Firmware: 01.00
2020-04-11 22:13:51,433 : INFO : EventManager : Event: ======'machine_var_fast_rgb_firmware'====== Args={'change': True, 'value': '01.00', 'prev_value': None}
2020-04-11 22:13:51,433 : INFO : EventManager : Event: ======'machine_var_fast_rgb_model'====== Args={'change': True, 'value': 'FP-CPU-002-2', 'prev_value': None}
2020-04-11 22:13:51,433 : INFO : EventManager : Event: ======'machine_var_credits_string'====== Args={'change': True, 'value': 'FREE PLAY', 'prev_value': None}
2020-04-11 22:13:51,964 : INFO : EventManager : Event: ======'machine_var_player1_score'====== Args={'change': True, 'value': 107, 'prev_value': None}
2020-04-11 22:13:51,964 : INFO : EventManager : Event: ======'machine_var_mpf_version'====== Args={'change': True, 'value': 'MPF v0.52.9', 'prev_value': None}
2020-04-11 22:13:51,964 : INFO : EventManager : Event: ======'machine_var_mpf_extended_version'====== Args={'change': True, 'value': 'MPF v0.52.9, Config version:5, Show version: 5, BCP version:1.1', 'prev_value': None}
2020-04-11 22:13:51,964 : INFO : EventManager : Event: ======'machine_var_python_version'====== Args={'change': True, 'value': '3.5.4', 'prev_value': None}
2020-04-11 22:13:51,964 : INFO : EventManager : Event: ======'machine_var_platform'====== Args={'change': True, 'value': 'Windows-10-10.0.18362-SP0', 'prev_value': None}
2020-04-11 22:13:51,964 : INFO : EventManager : Event: ======'machine_var_platform_system'====== Args={'change': True, 'value': 'Windows', 'prev_value': None}
2020-04-11 22:13:51,964 : INFO : EventManager : Event: ======'machine_var_platform_release'====== Args={'change': True, 'value': '10', 'prev_value': None}
2020-04-11 22:13:51,964 : INFO : EventManager : Event: ======'machine_var_platform_version'====== Args={'change': True, 'value': '10.0.18362', 'prev_value': None}
2020-04-11 22:13:51,964 : INFO : EventManager : Event: ======'machine_var_platform_machine'====== Args={'change': True, 'value': 'AMD64', 'prev_value': None}
2020-04-11 22:13:51,964 : INFO : EventManager : Event: ======'init_phase_1'====== Args={}
2020-04-11 22:13:52,512 : INFO : ConfigProcessor : Loading config from cache: C:\Users\MISSIO~1\AppData\Local\Temp\d6bb1cdfa60c1f50f35785cba55875d1.mpf_cache
2020-04-11 22:13:52,559 : INFO : ConfigProcessor : Loading config from cache: C:\Users\MISSIO~1\AppData\Local\Temp\32e6b619402cb4da5981e97ecb1f6408.mpf_cache
2020-04-11 22:13:52,574 : INFO : ConfigProcessor : Loading config from cache: C:\Users\MISSIO~1\AppData\Local\Temp\47fed2ef5afbaf0c19527a565aa191d9.mpf_cache
2020-04-11 22:13:52,574 : INFO : ConfigProcessor : Loading config from cache: C:\Users\MISSIO~1\AppData\Local\Temp\c721f48534ae43d3f9c4e17312560aaa.mpf_cache
2020-04-11 22:13:52,621 : INFO : ConfigProcessor : Loading config from cache: C:\Users\MISSIO~1\AppData\Local\Temp\c81a0f1062502e33bbed66b9eae15858.mpf_cache
2020-04-11 22:13:52,637 : INFO : ConfigProcessor : Loading config from cache: C:\Users\MISSIO~1\AppData\Local\Temp\1a49828cb8454c90fd195e3886327b9d.mpf_cache
2020-04-11 22:13:52,652 : INFO : ConfigProcessor : Loading config from cache: C:\Users\MISSIO~1\AppData\Local\Temp\6dbb84b4a2bd3a6642f95ce5744c7797.mpf_cache
2020-04-11 22:13:52,668 : INFO : ConfigProcessor : Loading config from cache: C:\Users\MISSIO~1\AppData\Local\Temp\4c74177f109f95ed9599c78880646655.mpf_cache
2020-04-11 22:13:52,699 : INFO : ConfigProcessor : Loading config from cache: C:\Users\MISSIO~1\AppData\Local\Temp\3183d529c1c05723ae7f7f27f6d76374.mpf_cache
2020-04-11 22:13:52,730 : INFO : ConfigProcessor : Loading config from cache: C:\Users\MISSIO~1\AppData\Local\Temp\4ea733655e2f71aef4d6f646b7999fe0.mpf_cache
2020-04-11 22:13:52,746 : INFO : ConfigProcessor : Loading config from cache: C:\Users\MISSIO~1\AppData\Local\Temp\5b0c10fb1ea3d696f3389c798402fbbd.mpf_cache
2020-04-11 22:13:52,762 : INFO : ConfigProcessor : Loading config from cache: C:\Users\MISSIO~1\AppData\Local\Temp\8e537f3f1075ad5ff3f7e8ba8228812c.mpf_cache
2020-04-11 22:13:52,777 : INFO : ConfigProcessor : Loading config from cache: C:\Users\MISSIO~1\AppData\Local\Temp\e316602f2754df2a40ebb1b620c83c27.mpf_cache
2020-04-11 22:13:52,793 : INFO : ConfigProcessor : Loading config from cache: C:\Users\MISSIO~1\AppData\Local\Temp\2476b3e7b98dcc7e56449320299b63be.mpf_cache
2020-04-11 22:13:52,808 : INFO : ConfigProcessor : Loading config from cache: C:\Users\MISSIO~1\AppData\Local\Temp\0db36da4b9aa41dcdeae696ef4ec8d87.mpf_cache
2020-04-11 22:13:52,824 : WARNING : ConfigProcessor : Config file in cache changed: E:\POKEMON - 4 - ATTRACT AND HIGH SCORE DISPLAYS\modes\pichu\config\pichu.yaml
2020-04-11 22:13:52,824 : INFO : ConfigProcessor : Loading config from file E:\POKEMON - 4 - ATTRACT AND HIGH SCORE DISPLAYS\modes\pichu\config\pichu.yaml.
2020-04-11 22:13:52,965 : INFO : ConfigProcessor : Loading config: E:\POKEMON - 4 - ATTRACT AND HIGH SCORE DISPLAYS\modes\pichu\config\pichu.yaml
2020-04-11 22:13:52,980 : INFO : ConfigProcessor : Config file cache created: C:\Users\MISSIO~1\AppData\Local\Temp\ead1ab3e53925d446b3cb0becf429113.mpf_cache
2020-04-11 22:13:53,090 : INFO : ConfigProcessor : Loading config from cache: C:\Users\MISSIO~1\AppData\Local\Temp\5a22bfd3cd388f17bd2b6acbd36605ae.mpf_cache
2020-04-11 22:13:53,106 : INFO : ConfigProcessor : Loading config from cache: C:\Users\MISSIO~1\AppData\Local\Temp\5903aae11c08aba35176e5c1f4c1be59.mpf_cache
2020-04-11 22:13:53,137 : INFO : ConfigProcessor : Loading config from cache: C:\Users\MISSIO~1\AppData\Local\Temp\f9a13da868835514a4e555019188716d.mpf_cache
2020-04-11 22:13:53,152 : WARNING : ConfigProcessor : Config file in cache changed: E:\POKEMON - 4 - ATTRACT AND HIGH SCORE DISPLAYS\modes\attract\config\attract.yaml
2020-04-11 22:13:53,152 : INFO : ConfigProcessor : Loading config from file c:\users\mission pinball\appdata\local\programs\python\python35\lib\site-packages\mpf\modes\attract\config\attract.yaml.
2020-04-11 22:13:53,168 : INFO : ConfigProcessor : Loading config: c:\users\mission pinball\appdata\local\programs\python\python35\lib\site-packages\mpf\modes\attract\config\attract.yaml
2020-04-11 22:13:53,168 : INFO : ConfigProcessor : Loading config from file E:\POKEMON - 4 - ATTRACT AND HIGH SCORE DISPLAYS\modes\attract\config\attract.yaml.
2020-04-11 22:13:53,293 : INFO : ConfigProcessor : Loading config: E:\POKEMON - 4 - ATTRACT AND HIGH SCORE DISPLAYS\modes\attract\config\attract.yaml
2020-04-11 22:13:53,293 : ERROR : asyncio : Exception in callback EventManager._async_handler_done(<QueuedEvent>)(<Task finishe...': '20s'}]",)>) at c:\users\mission pinball\appdata\local\programs\python\python35\lib\site-packages\mpf\core\events.py:96
handle: <Handle EventManager._async_handler_done(<QueuedEvent>)(<Task finishe...': '20s'}]",)>) at c:\users\mission pinball\appdata\local\programs\python\python35\lib\site-packages\mpf\core\events.py:96>
Traceback (most recent call last):
  File "c:\users\mission pinball\appdata\local\programs\python\python35\lib\asyncio\events.py", line 127, in _run
    self._callback(*self._args)
  File "c:\users\mission pinball\appdata\local\programs\python\python35\lib\site-packages\mpf\core\events.py", line 99, in _async_handler_done
    future.result()
  File "c:\users\mission pinball\appdata\local\programs\python\python35\lib\asyncio\futures.py", line 294, in result
    raise self._exception
  File "c:\users\mission pinball\appdata\local\programs\python\python35\lib\asyncio\tasks.py", line 240, in _step
    result = coro.send(None)
  File "c:\users\mission pinball\appdata\local\programs\python\python35\lib\site-packages\mpf\core\mode_controller.py", line 117, in load_modes
    self.machine.modes[mode] = self._load_mode(mode)
  File "c:\users\mission pinball\appdata\local\programs\python\python35\lib\site-packages\mpf\core\mode_controller.py", line 266, in _load_mode
    config = self._load_mode_config(mode_string)
  File "c:\users\mission pinball\appdata\local\programs\python\python35\lib\site-packages\mpf\core\mode_controller.py", line 184, in _load_mode_config
    store_to_cache=self.machine.options['create_config_cache'])
  File "c:\users\mission pinball\appdata\local\programs\python\python35\lib\site-packages\mpf\core\config_processor.py", line 112, in load_config_files_with_cache
    ignore_unknown_sections)
  File "c:\users\mission pinball\appdata\local\programs\python\python35\lib\site-packages\mpf\core\config_processor.py", line 142, in _load_config_file_and_return_loaded_files
    raise ConfigFileError("Config should be a dict: {}".format(config), self.log.name, "ConfigProcessor")
mpf.exceptions.ConfigFileError.ConfigFileError: Config File Error in ConfigProcessor: Config should be a dict: [{'slides': {'show_high_scores': {'widgets': [{'x': 'center', 'anchor_x': 'center', 'bold': True, 'anchor_y': 'center', 'type': 'Text', 'font_size': 60, 'y': 'top-100', 'text': 'HIGH SCORES'}, {'style': 'attract_mode_high_score_display_label', 'y': 'top-200', 'type': 'Text', 'text': '(machine|score1_label)'}, {'style': 'attract_mode_high_score_display_name', 'y': 'top-200', 'type': 'Text', 'text': '(machine|score1_name)'}, {'style': 'attract_mode_high_score_display_score', 'y': 'top-200', 'type': 'Text', 'text': '(machine|score1_value)'}, {'style': 'attract_mode_high_score_display_label', 'y': 'top-240', 'type': 'Text', 'text': '(machine|score2_label)'}, {'style': 'attract_mode_high_score_display_name', 'y': 'top-240', 'type': 'Text', 'text': '(machine|score2_name)'}, {'style': 'attract_mode_high_score_display_score', 'y': 'top-240', 'type': 'Text', 'text': '(machine|score2_value)'}, {'style': 'attract_mode_high_score_display_label', 'y': 'top-280', 'type': 'Text', 'text': '(machine|score3_label)'}, {'style': 'attract_mode_high_score_display_name', 'y': 'top-280', 'type': 'Text', 'text': '(machine|score3_name)'}, {'style': 'attract_mode_high_score_display_score', 'y': 'top-280', 'type': 'Text', 'text': '(machine|score3_value)'}, {'x': 'center', 'anchor_x': 'center', 'bold': True, 'anchor_y': 'center', 'type': 'Text', 'font_size': 60, 'y': 'top-500', 'text': 'LOOP CHAMPION'}, {'style': 'attract_mode_high_score_display_label', 'y': 'top-600', 'type': 'Text', 'text': '(machine|loops1_label)'}, {'style': 'attract_mode_high_score_display_name', 'y': 'top-600', 'type': 'Text', 'text': '(machine|loops1_name)'}, {'style': 'attract_mode_high_score_display_score', 'y': 'top-600', 'type': 'Text', 'text': '(machine|loops1_value)'}]}}, 'time': '20s'}] Error Code: CFE-ConfigProcessor-ConfigProcessor
2020-04-11 22:13:53,418 : INFO : Machine : Starting the main run loop.
2020-04-11 22:13:53,418 : INFO : Machine : Shutting down...
2020-04-11 22:13:53,418 : INFO : EventManager : Event: ======'shutdown'====== Args={}
2020-04-11 22:13:53,433 : ERROR : FAST : Stop called on serial connection com5
2020-04-11 22:13:53,433 : ERROR : FAST : Stop called on serial connection com4
2020-04-11 22:13:53,699 : ERROR : root : Config File Error in ConfigProcessor: Config should be a dict: [{'slides': {'show_high_scores': {'widgets': [{'x': 'center', 'anchor_x': 'center', 'bold': True, 'anchor_y': 'center', 'type': 'Text', 'font_size': 60, 'y': 'top-100', 'text': 'HIGH SCORES'}, {'style': 'attract_mode_high_score_display_label', 'y': 'top-200', 'type': 'Text', 'text': '(machine|score1_label)'}, {'style': 'attract_mode_high_score_display_name', 'y': 'top-200', 'type': 'Text', 'text': '(machine|score1_name)'}, {'style': 'attract_mode_high_score_display_score', 'y': 'top-200', 'type': 'Text', 'text': '(machine|score1_value)'}, {'style': 'attract_mode_high_score_display_label', 'y': 'top-240', 'type': 'Text', 'text': '(machine|score2_label)'}, {'style': 'attract_mode_high_score_display_name', 'y': 'top-240', 'type': 'Text', 'text': '(machine|score2_name)'}, {'style': 'attract_mode_high_score_display_score', 'y': 'top-240', 'type': 'Text', 'text': '(machine|score2_value)'}, {'style': 'attract_mode_high_score_display_label', 'y': 'top-280', 'type': 'Text', 'text': '(machine|score3_label)'}, {'style': 'attract_mode_high_score_display_name', 'y': 'top-280', 'type': 'Text', 'text': '(machine|score3_name)'}, {'style': 'attract_mode_high_score_display_score', 'y': 'top-280', 'type': 'Text', 'text': '(machine|score3_value)'}, {'x': 'center', 'anchor_x': 'center', 'bold': True, 'anchor_y': 'center', 'type': 'Text', 'font_size': 60, 'y': 'top-500', 'text': 'LOOP CHAMPION'}, {'style': 'attract_mode_high_score_display_label', 'y': 'top-600', 'type': 'Text', 'text': '(machine|loops1_label)'}, {'style': 'attract_mode_high_score_display_name', 'y': 'top-600', 'type': 'Text', 'text': '(machine|loops1_name)'}, {'style': 'attract_mode_high_score_display_score', 'y': 'top-600', 'type': 'Text', 'text': '(machine|loops1_value)'}]}}, 'time': '20s'}] Error Code: CFE-ConfigProcessor-ConfigProcessor
Traceback (most recent call last):
  File "c:\users\mission pinball\appdata\local\programs\python\python35\lib\site-packages\mpf\commands\game.py", line 220, in __init__
    MachineController(mpf_path, machine_path, vars(self.args)).run()
  File "c:\users\mission pinball\appdata\local\programs\python\python35\lib\site-packages\mpf\core\machine.py", line 709, in run
    self._run_loop()
  File "c:\users\mission pinball\appdata\local\programs\python\python35\lib\site-packages\mpf\core\machine.py", line 769, in _run_loop
    raise self._exception['exception']
  File "c:\users\mission pinball\appdata\local\programs\python\python35\lib\asyncio\events.py", line 127, in _run
    self._callback(*self._args)
  File "c:\users\mission pinball\appdata\local\programs\python\python35\lib\site-packages\mpf\core\events.py", line 99, in _async_handler_done
    future.result()
  File "c:\users\mission pinball\appdata\local\programs\python\python35\lib\asyncio\futures.py", line 294, in result
    raise self._exception
  File "c:\users\mission pinball\appdata\local\programs\python\python35\lib\asyncio\tasks.py", line 240, in _step
    result = coro.send(None)
  File "c:\users\mission pinball\appdata\local\programs\python\python35\lib\site-packages\mpf\core\mode_controller.py", line 117, in load_modes
    self.machine.modes[mode] = self._load_mode(mode)
  File "c:\users\mission pinball\appdata\local\programs\python\python35\lib\site-packages\mpf\core\mode_controller.py", line 266, in _load_mode
    config = self._load_mode_config(mode_string)
  File "c:\users\mission pinball\appdata\local\programs\python\python35\lib\site-packages\mpf\core\mode_controller.py", line 184, in _load_mode_config
    store_to_cache=self.machine.options['create_config_cache'])
  File "c:\users\mission pinball\appdata\local\programs\python\python35\lib\site-packages\mpf\core\config_processor.py", line 112, in load_config_files_with_cache
    ignore_unknown_sections)
  File "c:\users\mission pinball\appdata\local\programs\python\python35\lib\site-packages\mpf\core\config_processor.py", line 142, in _load_config_file_and_return_loaded_files
    raise ConfigFileError("Config should be a dict: {}".format(config), self.log.name, "ConfigProcessor")
mpf.exceptions.ConfigFileError.ConfigFileError: Config File Error in ConfigProcessor: Config should be a dict: [{'slides': {'show_high_scores': {'widgets': [{'x': 'center', 'anchor_x': 'center', 'bold': True, 'anchor_y': 'center', 'type': 'Text', 'font_size': 60, 'y': 'top-100', 'text': 'HIGH SCORES'}, {'style': 'attract_mode_high_score_display_label', 'y': 'top-200', 'type': 'Text', 'text': '(machine|score1_label)'}, {'style': 'attract_mode_high_score_display_name', 'y': 'top-200', 'type': 'Text', 'text': '(machine|score1_name)'}, {'style': 'attract_mode_high_score_display_score', 'y': 'top-200', 'type': 'Text', 'text': '(machine|score1_value)'}, {'style': 'attract_mode_high_score_display_label', 'y': 'top-240', 'type': 'Text', 'text': '(machine|score2_label)'}, {'style': 'attract_mode_high_score_display_name', 'y': 'top-240', 'type': 'Text', 'text': '(machine|score2_name)'}, {'style': 'attract_mode_high_score_display_score', 'y': 'top-240', 'type': 'Text', 'text': '(machine|score2_value)'}, {'style': 'attract_mode_high_score_display_label', 'y': 'top-280', 'type': 'Text', 'text': '(machine|score3_label)'}, {'style': 'attract_mode_high_score_display_name', 'y': 'top-280', 'type': 'Text', 'text': '(machine|score3_name)'}, {'style': 'attract_mode_high_score_display_score', 'y': 'top-280', 'type': 'Text', 'text': '(machine|score3_value)'}, {'x': 'center', 'anchor_x': 'center', 'bold': True, 'anchor_y': 'center', 'type': 'Text', 'font_size': 60, 'y': 'top-500', 'text': 'LOOP CHAMPION'}, {'style': 'attract_mode_high_score_display_label', 'y': 'top-600', 'type': 'Text', 'text': '(machine|loops1_label)'}, {'style': 'attract_mode_high_score_display_name', 'y': 'top-600', 'type': 'Text', 'text': '(machine|loops1_name)'}, {'style': 'attract_mode_high_score_display_score', 'y': 'top-600', 'type': 'Text', 'text': '(machine|loops1_value)'}]}}, 'time': '20s'}] Error Code: CFE-ConfigProcessor-ConfigProcessor
